name = "LeanTemplate"
version = "0.1.0"
description = "" # one line: what this project formalizes
keywords = ["math"]
homepage = "https://github.com/0stellensatz/LeanTemplate"
license = "Apache-2.0"
defaultTargets = ["LeanTemplate"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[require]]
name = "LeanPrism"
git = "https://codeberg.org/wvhulle/lean-prism.git"
rev = "main"

[[lean_lib]]
name = "LeanTemplate"
